import type { NextPage } from "next";
import { useContext } from "react";
import Scene from "../components/house/scene";
import { Box } from "../components/house/examples";
import Background from "../components/common/Bg";
import { login } from "../lib/contract/utils";
import ContractContext from "../lib/context/contractProvider";
import Link from "next/link";

const Home: NextPage = () => {
  const { walletConnection } = useContext(ContractContext);
  console.log(walletConnection);
  return (
    <Background
      title={"Capitalism innit"}
      description={"Generated by red bull"}
    >
      <main className="bg-gray-700 flex-1 text-center">
        <h1>Capitalism</h1>
        <Scene>
          <Box position={[0, 0, 0]} />
        </Scene>
        <button onClick={() => login(walletConnection)}>Login</button>
        {walletConnection.isSignedIn() && <Link href="/game">Game</Link>}
      </main>
    </Background>
  );
};

export default Home;
