import type { NextPage } from "next";
import { useContext } from "react";
import BirdsPage from "../components/house/scene";
import Background from "../components/common/Bg";
import { login } from "../lib/wallet/utils";
import ContractContext from "../lib/context/contractProvider";

const Home: NextPage = () => {
  const { walletConnection } = useContext(ContractContext);
  console.log(walletConnection);
  return (
    <Background
      title={"Capitalism innit"}
      description={"Generated by create next app"}
      favicon={
        "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏠</text></svg>"
      }
    >
      <main className="bg-gray-700 flex-1 text-center">
        <h1>Capitalism</h1>
        <BirdsPage />
        <button onClick={() => login(walletConnection)}>Login</button>
      </main>
    </Background>
  );
};

export default Home;
