import type { NextPage } from "next";

import { useContext } from "react";
import Scene from "../components/common/Scene";
import { Triangle } from "../components/game/examples";
import Background from "../components/common/Bg";
import { login } from "../lib/contract/utils";
import ContractContext from "../lib/context/contractProvider";
import Link from "next/link";

const Home: NextPage = () => {
  const { walletConnection } = useContext(ContractContext);
  return (
    <Background
      title={"Capitalism innit"}
      description={"Generated by red bull"}
    >
      <main className="bg-gray-700 text-center flex flex-auto">
        <div className="relative w-full">
          <Scene bgColor={["black"]} showBlur={true}>
            <Triangle />
          </Scene>
          <button className="absolute top-1/2 w-full p-4 text-2xl font-bold flex flex-row justify-center bg-black hover:opacity-100 text-white opacity-90">
            {walletConnection.isSignedIn() ? (
              <Link href="/game">Go to Lobby</Link>
            ) : (
              <button
                className="w-full"
                onClick={() => login(walletConnection)}
              >
                Login
              </button>
            )}
          </button>
        </div>
      </main>
    </Background>
  );
};

export default Home;
